title: Spiraline
email: spiraline@naver.com
description: >- 
  Portofolio / Blog
baseurl: ""
url: "https://spiraline.github.io"
github_username:  spiraline
github_repo_url: "https://github.com/Spiraline"
pages: about develop

version: 1.2

# Build settings
theme: minima
plugins_dir:
  - jekyll-feed


# Resume settings
sass:
  sass_dir: _sass
  style: compressed