title: Spiralineeeeeeeeee
email: spiraline@snu.ac.kr
description: >- 
  Spiraline's Blog
baseurl: ""
url: "https://spiraline.github.io"
github_username:  spiraline
github_repo_url: "https://github.com/Spiraline"
page_list: develop

version: 1.2

# Build settings
theme: minima
plugins_dir:
  - jekyll-feed

# Resume settings
sass:
  sass_dir: _sass
  style: compressed