title: Spiraline
email: spiraline@naver.com
description: >- 
  와 신기하다
baseurl: ""
url: "https://spiraline.github.io"
github_username:  spiraline
github_repo_url: "https://github.com/Spiraline"

version: 1.2

# Build settings
theme: minima
plugins_dir:
  - jekyll-feed